/**
 * Environment Generator
 * Spec: 07-Terraform-Provisioning-Engine
 *
 * Auto-generates a per-service Terraform environment directory at
 * `terraform/environments/<service-id>/` containing:
 *  - main.tf — references the appropriate module and passes variables
 *  - backend.tf — per-service S3 remote state configuration
 *  - terraform.tfvars.json — service-specific variable values
 *
 * This ensures each service has an isolated Terraform workspace
 * with its own state path in S3.
 */

import fs from 'fs/promises';
import path from 'path';
import { logger } from '../../utils/logger.js';
import type { EnvironmentConfig } from './types.js';

// ---------------------------------------------------------------------------
// Template generators
// ---------------------------------------------------------------------------

function generateMainTf(cfg: EnvironmentConfig): string {
  // Determine relative path from environments/<service-id>/ to modules/<module>/
  // modulePath is like "terraform/modules/nodejs-api"
  const moduleName = path.basename(cfg.modulePath);

  return `# Auto-generated by SCAPE Provisioning Engine
# Service: ${cfg.serviceName} (${cfg.serviceId})
# Do not edit manually — changes will be overwritten on re-provision.

module "service" {
  source = "../../modules/${moduleName}"

  service_name = var.service_name
  service_id   = var.service_id
  region       = var.region
  environment  = var.environment
  owner_team   = var.owner_team
  tags         = var.tags
}

# Pass-through variables
variable "service_name" {
  type = string
}

variable "service_id" {
  type = string
}

variable "region" {
  type    = string
  default = "${cfg.region}"
}

variable "environment" {
  type    = string
  default = "${cfg.environment}"
}

variable "owner_team" {
  type = string
}

variable "tags" {
  type    = map(string)
  default = {}
}

# Outputs from the module
output "service_endpoint" {
  value = module.service.service_endpoint
}

output "resource_arns" {
  value = module.service.resource_arns
}
`;
}

function generateBackendTf(cfg: EnvironmentConfig): string {
  const state = cfg.stateBackend;

  return `# Auto-generated by SCAPE Provisioning Engine
# Remote state for service: ${cfg.serviceId}

terraform {
  backend "s3" {
    bucket         = "${state.bucket}"
    key            = "${state.key}"
    region         = "${state.region}"
    dynamodb_table = "${state.dynamodbTable}"
    encrypt        = ${state.encrypt}
  }
}
`;
}

function generateTfVarsJson(cfg: EnvironmentConfig): string {
  const vars = {
    service_name: cfg.serviceName,
    service_id: cfg.serviceId,
    region: cfg.region,
    environment: cfg.environment,
    owner_team: cfg.ownerTeam,
    tags: {
      ...cfg.tags,
      ManagedBy: 'scape',
      ServiceId: cfg.serviceId,
      TeamId: cfg.ownerTeam,
    },
  };

  return JSON.stringify(vars, null, 2);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate the environment directory for a service.
 * Creates `terraform/environments/<service-id>/` with all required files.
 *
 * @returns The absolute path to the generated environment directory.
 */
export async function generateEnvironment(cfg: EnvironmentConfig): Promise<string> {
  // Resolve the environments directory relative to project root
  const projectRoot = path.resolve(process.cwd(), '..');
  const envDir = path.join(projectRoot, 'terraform', 'environments', cfg.serviceId);

  logger.info(
    { serviceId: cfg.serviceId, envDir },
    'Generating Terraform environment directory',
  );

  // Create directory (recursive in case parent doesn't exist)
  await fs.mkdir(envDir, { recursive: true });

  // Write all files in parallel
  await Promise.all([
    fs.writeFile(path.join(envDir, 'main.tf'), generateMainTf(cfg)),
    fs.writeFile(path.join(envDir, 'backend.tf'), generateBackendTf(cfg)),
    fs.writeFile(path.join(envDir, 'terraform.tfvars.json'), generateTfVarsJson(cfg)),
  ]);

  logger.info(
    { serviceId: cfg.serviceId, envDir },
    'Terraform environment directory generated successfully',
  );

  return envDir;
}

/**
 * Clean up the environment directory for a service (after destroy / decommission).
 */
export async function cleanupEnvironment(serviceId: string): Promise<void> {
  const projectRoot = path.resolve(process.cwd(), '..');
  const envDir = path.join(projectRoot, 'terraform', 'environments', serviceId);

  try {
    await fs.rm(envDir, { recursive: true, force: true });
    logger.info({ serviceId, envDir }, 'Terraform environment directory cleaned up');
  } catch (err: any) {
    logger.warn(
      { err: err.message, serviceId, envDir },
      'Failed to clean up Terraform environment directory',
    );
  }
}

/**
 * Check if an environment directory already exists for a service.
 */
export async function environmentExists(serviceId: string): Promise<boolean> {
  const projectRoot = path.resolve(process.cwd(), '..');
  const envDir = path.join(projectRoot, 'terraform', 'environments', serviceId);

  try {
    await fs.access(envDir);
    return true;
  } catch {
    return false;
  }
}
